apiVersion: v1
kind: Service
metaData:
  name:  result-service
  labels:
   name: result-service
   app: demo-voting-app
   
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app
  type:  NodePort
  ports:
  - port:  80
    targetPort:  80