apiVersion: v1
kind: Service
metadata:
  name:  voter-service
  labels:
   name: voter-service
   app: demo-voting-app
   
spec:
  selector:
    name: voting-app-pod
    app: demo-voting-app
  type:  NodePort
  ports:
  - port:  80
    targetPort:  80