apiVersion: v1
kind: Pod
metaData:
 name: voting-app-pod
 labels: demo-voting-app
spec:
 containers:
   - name: voting-app
     image: dockersamples/examplevotingapp_vote
     ports: 
      - containerPort: 80